### ISSUE TITLE
Hi sir, sorry for interrupted, can you help me about this?

### ISSUE THREAD

**Issue by jackxuan0305** [mrahmadhassankhan/chegg-bartleby-discord-bot#1]
this is the pictures for my issues
i used node . to run it, first, it show as the first pic, but it will automatic close it, and displayed an error (showed in second pics)
![image](https://user-images.githubusercontent.com/99300718/154832537-7b585b6c-4b6c-45c6-95ae-f222afc42deb.png)
![image](https://user-images.githubusercontent.com/99300718/154832612-ef48b0ee-3353-497a-bf18-0570ce9362f1.png)

**Comment by mrahmadhassankhan** [comment]
Ok dear let me check the issue

**Comment by mrahmadhassankhan** [comment]
The bot.js is modified

**Comment by jackxuan0305** [comment]
thank you so much!
