### ISSUE TITLE
Hi sir, sorry for interrupt again

### ISSUE THREAD

**Issue by jackxuan0305** [mrahmadhassankhan/chegg-bartleby-discord-bot#3]
Sir, can i ask some question? 
Sir, can you recommend me some paid captcha website for chegg?  I searched on google for a long time but unfortunately I didn't find anything. 

Sir, for the bartleby one, the https://www.bartleby.com/auth?action=login&redirect=https%3A%2F%2Fwww.bartleby.com%2F seem not correct because its not found on the bartleby website (show as the picture below)

![image](https://user-images.githubusercontent.com/99300718/154900536-f4e2237c-c59f-4b8b-8314-b573eeb4d921.png)

**Comment by mrahmadhassankhan** [comment]
make changes to the url 
https://www.bartleby.com/login?redirect=https%3A%2F%2Fwww.bartleby.com%2F
