### ISSUE TITLE
Requesting for help

### ISSUE THREAD

**Issue by GJungao** [mrahmadhassankhan/chegg-bartleby-discord-bot#4]
Hello this is not an issue but I just wanted to know if you can walk me through this, I do not have enough knowledge to do these things but I would really appreciate if you can help me on how to download or make a discord bot. I hope that you see this and you agree I will leave my discord here Urameshi #9834

**Comment by warwudo** [comment]
i've tried it and find that chegg human verification is hard to bypass, i cannot login. I haven't try to bartleby.

**Comment by avtar312** [comment]
I send u request

**Comment by avtar312** [comment]
Contact at telegram for help @Khnh6

**Comment by mrahmadhassankhan** [comment]
**You have a little bit knowledge of java script in order to customize it according to you need**
