### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by warwudo** [mrahmadhassankhan/chegg-bartleby-discord-bot#5]
![image](https://user-images.githubusercontent.com/100148848/157814108-d51d4711-4f24-44b4-87f4-11662c99b879.png)

Pop up windows is out, but when i need to verification "press and hold" button, the windows suddenly close and the error occur. Can you help me sir, please?

**Comment by Ednn0nd1au** [comment]
same issue

**Comment by Ednn0nd1au** [comment]
same issue @mrahmadhassankhan

**Comment by mrahmadhassankhan** [comment]
instead of "#emailForSignIn" use "#login_email_input" on line 173 
and  use "#login_password_input" on line 176  instead of "#passwordForSignIn "
and replace the line number 179 with 
await page.click(
    "html > body > div:nth-child(1) > main > div > div:nth-child(2) > div > div > div > div:nth-child(1) > div > form > button"
  );
@Ednn0nd1au @warwudo
