### ISSUE TITLE
CLIENT_MISSING_INTENTS ERROR

### ISSUE THREAD

**Issue by richardyylouie** [mrahmadhassankhan/chegg-bartleby-discord-bot#6]
Updated username, password and Discord token. Not sure what else I'm missing. Thank you for sharing code too.

global.username = 'CHEGG LOGIN GOES HERE'
global.password = 'CHEGG PASS GOES HERE'
global.discordlogin = 'KEY GOES HERE'

Installed all dependencies as required and ran using node but getting error 

Logged in as Bartleby Bot#12345
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'user-agents'
Require stack:
- C:\Bartleby-Discord-Bot-main\bot.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at login_bartleby (C:\Bartleby-Discord-Bot-main\bot.js:172:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\Bartleby-Discord-Bot-main\bot.js' ]
}

**Comment by mrahmadhassankhan** [comment]
user agents module not installed 
install it using 
npm i user-agents

**Comment by mrahmadhassankhan** [comment]
also if you still facing after installing too then follow these steps 

below this code 
`global.username = 'CHEGG LOGIN GOES HERE'
global.password = 'CHEGG PASS GOES HERE'
global.discordlogin = 'KEY GOES HERE'`

add the below lines below it ok

`const client = new Discord.Client({
  intents: [
    Discord.GatewayIntentBits.Guilds,
    Discord.GatewayIntentBits.GuildMessages,
  ],
});`
